const PRACTICE_CODE = 'JC67H7';
const BASE_URL = `http://localhost:3001/api/practice/${PRACTICE_CODE}`;
const NUM_PLAYERS = 25;

//Generated by Google Gemini, seems like a good use case for AI to generate seed data script
//Also the ready a court didn't really work for me so I manually readied 4 courts and I'm not sure why it didn't work, it was an internal server error
async function seedData() {
  console.log(`🌱 Starting seed script for practice: ${PRACTICE_CODE}\n`);

  try {
    // ---------------------------------------------------------
    // STEP 1: Join Practice 25 times
    // ---------------------------------------------------------
    console.log(`[Step 1] Creating ${NUM_PLAYERS} players...`);
    const playerIds = [];

    for (let i = 1; i <= NUM_PLAYERS; i++) {
      const username = `player${i}`;
      const password = `pass${i}`;

      const response = await fetch(`${BASE_URL}/join`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username, password })
      });

      if (!response.ok) throw new Error(`Join failed for ${username}: ${response.statusText}`);
      
      const data = await response.json();
      
      // Locate the newly created player in the returned players array
      const newPlayer = data.result.players.find(p => p.username === username);
      if (!newPlayer || !newPlayer.id) {
        throw new Error(`Could not find id for ${username} in the response array`);
      }

      playerIds.push(newPlayer.id);
      console.log(`   ✅ Joined ${username} -> ID: ${newPlayer.id}`);
    }
    console.log(`\n🎉 Successfully collected ${playerIds.length} player IDs.\n`);

    // ---------------------------------------------------------
    // STEP 2: Enqueue all 25 players
    // ---------------------------------------------------------
    console.log(`[Step 2] Enqueuing ${NUM_PLAYERS} players...`);
    const queueChipIdsSet = new Set();

    for (let i = 0; i < playerIds.length; i++) {
      const playerId = playerIds[i];

      const response = await fetch(`${BASE_URL}/player/enqueue`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ playerId })
      });

      if (!response.ok) throw new Error(`Enqueue failed for playerId ${playerId}: ${response.statusText}`);
      
      const data = await response.json();
      // data.queue is an array of chips. If chips exist, grab the latest created chip's _id
      if (Array.isArray(data.queue) && data.queue.length > 0) {
        const latestChip = data.queue[data.queue.length - 1];
        if (latestChip && latestChip._id) {
          queueChipIdsSet.add(latestChip._id);
        }
      }
      console.log(`   ✅ Enqueued player ${i + 1}/${NUM_PLAYERS}`);

    }
    // Convert Set of unique chip IDs to an array
    const queueChipIds = Array.from(queueChipIdsSet);
    console.log(`\n🎉 Successfully collected ${queueChipIds.length} complete queue chip IDs.\n`);

    // ---------------------------------------------------------
    // STEP 3: Ready up 4 courts
    // ---------------------------------------------------------
    console.log(`[Step 3] Assigning first 4 chips to courts...`);
    
    for (let courtNumber = 1; courtNumber <= 4; courtNumber++) {
      // Get the corresponding queue chip (index 0 for court 1, etc.)
      const queueChipId = queueChipIds[courtNumber - 1];

      const response = await fetch(`${BASE_URL}/queue/ready`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ queueChipId, courtNumber })
      });

      if (!response.ok) {
        throw new Error(`Ready up failed for Court ${courtNumber}: ${response.statusText} and ${response.status}`);
      }

      console.log(`   🎾 Assigned Queue Chip ${queueChipId} to Court ${courtNumber}`);
    }

    console.log(`\n✅ Database seeding complete!`);

  } catch (error) {
    console.error(`\n❌ Seeding failed:`, error.message);
  }
}

// Execute the async function
seedData();